export default [
    {   "Classrooms Items" : "Atik Salklas La",
        "IMAGE": "assets/classroom-items.jpg",
        "Chair":  "Chèz",
        "Clock" :   "Revèy",
        "Geographic Map" : "Kat jeyografik", 
        "Computer" :  "Konpitè",  
        "Pen" : "Plim",
        "Pencil" : "Kreyon",
        "Ruler" :  "Règ",
        "Desk" : "Biwo",
        "Notebook" : "Kaye", 
        "Number" : "Nonb",
        "Eraser" : "Góm", 
        "Teacher" :  "Pwofesè",  
        "Student" : "Elèv", 
        "Books" : "Liv",
        "Board" : "Tablo",
        "Paper" :  "Papye", 
        "Backpack" :  "Valiz",
        "Scissors" :  "Sizo",
        "Pencil Case" :  "Ka Kreyon",
        "Pencil Sharpener" : " Tay Kreyon",
        "Calculator" :  "Kalkilatris",
        "Printer" :  "Printè",
        "Calendar" :  "Kalandriye",
        "Chalk" :  "Lakre",
        "Markers" :  "Makè",
        "Posters" :  "Afich",
        "Decorations" :  "Dekorasyon",
        "Carpets" :  "Kapèt",
        "Lights" :  "Limyè",
        "Doors" :  "Pot"
    },
    {  
        "City Buildings" : "Vil Bilding Yo" ,
        "IMAGE": "assets/city-buildings.jpg",
       "Bank" : "La Bank",
       "Hotel" : "ótel" ,
       "Church" : "Legliz",
       "Library" : "Bibliyotèk",
       "Coffee shop" : "Magazen kafe" ,
       "Grocery Store" : "Makèt",
       "Gym" : "Gym" ,
       "School" : "Lekòl" ,
       "Hospital" : "Lopital",
       "Bakery" : "Boulanje",
       "Gas station" : "Stasyon Gaz",
       "Police station" : "Pòs Polis",
       "Post office" : "Lapòs" ,
       "Movie theater" : "Cinema" ,
       "Apartment" : "Apatman an",
       "Movie Theater" :  "Cinema",
       "Theater" :  "Teyat",
       "Dance Studio" :  "Studio Dans",
       "Furniture Store" :  "Magazen Mèb",
       "Barbershop" : "Barbershop",
       "Courthouse" :  "Tribinal",
       "Pharmacy" :  "Famasi",
       "Nail Salon" :  "Salon Zong",
       "Restaurant" :  "Restoran",
       "Laundry" :  "Lesiv",
       "Doctors Office" :  "Doktè Biwo" ,
       "Colleges" :  "Kolèj yo",
       "Swimming Pools" :  "Pisin",
       "Train Station" :  "Stasyon Train",
    },
    {
        "Jobs" : "Travay", 
        "IMAGE": "assets/jobs.jpg",
        "Actor" :  "Aktè",
        "Cashier" : "Kesye",
        "Actress" : "Aktris", 
        "Pilot" : "Aviator",
        "Dentist" : "Dantis",
        "Doctor" : "Doktè",
        "Artist" : "Atis" ,
        "Accountant" : "Kontab",
        "Nurse" : "Enfimyè",
        "Reporter" : "Repòtè",
        "Secretary" : "Sekretè",
        "Lawyer" : "Avoka",
        "Musician" : "Mizisyen",
        "Writer" : "Ekriven",
        "Engineer" : "Enjenyè",
        "Arichitect" :  "Achitek",
        "Mechanic" :  "Mekanisyen",
        "Businessman" :  "Biznisman",
        "Driver" :  "Chofè",
        "Carpenter" :  "Bòs Chapant",
        "Programmer" :  "Pwogramè Konpitè",
        "Chef" :  "Chèf",
        "Hairdresser" :  "Kwafèz",
        "Gardener" :  "Jardinyé",
        "Pastor" :  "Pasteur",
        "Fisherman" :  "Pechè pwason",
        "Soilder" :  "Sòlda",
        "Translator" :  "Tradiktè",
        "Philosopher" :  "Filozòf",
        "Scientist" :  "Syantis" 
        
    },
    {
        "The Body" :"Kò a",
        "IMAGE": "assets/the-human-body.jpg",
        "Brain"  : "Sèvo",
        "Foot"  : "Pye",
        "Leg" : "Janmbe",
        "Head" : "Tèt",
        "Arm" : "Bra",
        "Heart" : "Kè",
        "Skin" : "Po",
        "Lip" : "Lèv",
        "Hair" : "Cheve",
        "Nose" : "Nen",
        "Stomach" : "Lestomak",
        "Bone" : "Zo" ,
        "Knee" : "Jenou",
        "Chest" : "Pwatrin" ,
        "Hand" : "Men",
        "Shoulder" : "Zepol",
        "Back" : "Do",
        "Waist" : "Ren",
        "Forehead" : "Front",
        "Thigh" : "Kwis Pye",
        "Teeth" : "Dan",
        "Ear" : "Zorey" ,
        "Finger" : "Dwet Yo",
        "Toes" : "Zotey Yo",
        "Tongue" : "Lang",
        "Jaw" : "Machwa",
        "Eye" : "Zye",
        "Muscles" : "Misk",
        "Nails" : "Zong",
        "Wrist" : "Ponyèt"
    },
    {
        "Feelings" : "Santiman"  ,
        "IMAGE": "assets/emotions.jpg",
        "Hot" : "Cho" ,
        "Cold" : "Frèt",
        "Pain" : "Doulè",
        "Sick" : "Malad",
        "Hungry" : "Grangou",
        "Disgusted"  : "Degoutan",
        "Thirsty" : "Swaf"  ,
        "Angry" : "Fache",
        "Scared" : "Pè",
         "Sad" : "Tris",
         "Happy" : "Kontan" ,
         "Tired" : "Fatige" ,
         "Embarrassed" : "Anbarase",
         "Comfortable" : "Konfòtab",
         "Confused" : "Konfonn"  ,
        "Full" : "Plen",
        "Joyful" : "Jwa",
        "Peace" : "Lapè",
        "Calm" : "Kalm",
        "Surprised" : "Sezis",
        "Bored" : "Anniye",
        "Excited" : "Eksite",
        "Proud" : "Fyè",
        "Good" : "Byen",
        "Sympathy" : "Senpati",
        "Curios" : "Kiryozite",
        "Grateful" : "Rekonesan",
        "Cofident" : "Konfidan",
        "Love" : "Renmen",
        "Brave" : "Brav"
         
    },
    {
        "Animals" : "Bèt yo" ,
        "IMAGE": "assets/animals.jpg",
        "Goat" : "Kabrit",
        "Dog" : "Chen",
        "Snake"  : "Koulèv",
        "Cat" : "Chat",
        "Mouse" : "Sourit",
        "Loin"  : "Lyon",
        "Whale" : "Balèn",
        "Snail" : "Kalmason",
        "Frog" : "Krapo",
        "Crab" : "Krab",
        "Fish" : "Pwason",
        "Dolphin" : "Dofen" ,
        "Bear" : "Lous",
        "Monkey" : "Makak",
        "Cow" : "Bèf",
        "Tiger" : "Tig",
        "Lamb" : "Mouton",
        "Pig" : "Kochon",
        "Deer" : "Sèf" ,
        "Skunk" : "Pipirit",
        "Donkey" : "Bourik",
        "Gorilla" : "Goril",
        "Elephant" : "Elefan",
        "Giraffe" : "Jiraf",
        "Pigeon" : "Pijon",
        "Camel" : "Chamo",
        "Rhinoceros" : "Rinoseros",
        "Horse" : "Chwal",
        "Butterfly" : "Papiyon",
        "Parrot" : "Jako"

    },
    {
       "Foods" : " Dives Kalite Manje " ,
       "IMAGE": "assets/fruits-and-vegatables.jpg",
       "Grapes" : "Rezen",
       "Apples" : "Ponm" ,
       "Bananas" : "Bannann",
       "Oranges" : "Zoranj",
       "Lemons" : "Sitron",
       "Beets" : "Bètrav",
       "Papayas" : "Papay",
       "Watermelon" : "Pastèk",
       "Onions" : "Zonyon",
       "Garlic"  : "Lay",
       "Carrots"  : "Kawòt",
       "Peas" : "Pwa Frans",
       "Beans" : "Pwa" ,
       "Tomatoes"  : "Tomat",
       "Corn" : "Mayi",
       "Pineapples" : "Anana",
       "Mango" : "Mango",
       "Peanuts" : "Pistache" ,
       "Coconuts" : "Kokoye",
       "Rice" : "Diri",
       "Plantains" : "Bannann",
       "Fried Pork" : "Griot",
       "Pressed Plantains" : "Bannann Peze",
       "Cheese" : "Fwomaj",
       "Spaghetti" : "Espageti",
       "Crab" : "Krab",
       "Bread" : "Pen",
       "Peanut Butter" : "Manba",
       "Cake" : "Gato",
    },
    {
        "The Bible" : "Bib La",
        "IMAGE": "assets/the-bible.jpg",
        "Jesus" : "Jezi",
        "Abraham" : "Abraram",
        "Isreal" : "Izrael",
        "David" : "David",
        "Cain" : "Cayen",
        "Abel" : "Abel",
        "Moses" : "Moyiz",
        "God" : "Bondye",
        "Samson" : "Samson",
        "Great Flood" : "Gwo Inondasyon",
        "Adam" : "Adam",
        "Eve" : "Eve",
        "10 Commandments" : "Dis Komandman",
        "The Holy Spirit" : "Lespri Sen",
        "Aaron" : "Arawon",
        "Methuselah" : "Metouchela",
        "Jericho" : "Jeriko",
        "Daniel" : "Danyèl",
        "Samuel" : "Samyèl",
        "Job" : "Job",
        "Esther" : "Estè",
        "Mary" : "Mary" ,
        "Dorcas" : "Dorcas",
        "Peter" : "Pye",
        "Paul" : "Pol",
        "Golgotha" : "Golgota",
        "Eden" : "Edenn",
        "Miriam" : "Miryam",
        "Ruth" : "Rut",
        "Baptism" : "Batèm",
    },
    {

        "Songs" : "Chants",
        "IMAGE": "assets/songs.jpg",
        "Quelle assurance" : "Blessed Assurance" ,
        "Wi mwen Kwe ou Ap Reye" : "Mwen kwe ou se bondye"  ,
        "Anyo Imole" : "Leve men-m devan majestew" ,
        "Menmm Jan Plant" : "As the Deer Panteth",
        "Se Jou Map Konte" : "Paket Mwen Mare",
        "Je Mwen Pap jamn sispan fixe ou" : "Vini kouvri mwen",
        "Kitem Kenbe wob ou Pi plis" : "Kite’m tande vwa’w pi plis",
        "ka gide pye moun ki pran move chemen" : "Gidem Segne pou-m",
        "Sa-k pou mwen yo" :  "Ma Va Restore",
        "Mwen Jezi" : "Sove Nanm",
        "Joyeux Anniversaire" : "Happy Birthday",
        "Merite La Gloire" : "Toi Seul Seigneur",
        "Tout Sa Ki Gen souf" : "Let Everything That Has Breath",
        "Nenpot Kote Mwen Ye" : "Konfye-m Nan Dye",
        "Brille Petite Etoile" : "Twinkle Little Star",
        "ABCDEFG song" : "Chant Alfabè a",
        "Bondye Ou Fidèl" : "Ou Janm Pa La" ,
        "Sou Yon Kwa" : "A Golgota",
        "He Knows My Name" : "Li konnen Nonm" ,
        "Mwen Adore W...Jezi" : "M-Konnen Ou Se Pitit la",
        "Ou Kon Lavi-m Purifye Mwen" : "Sentespri Sele Mwen",
        "Segne pale pou mwen" : "Pale pou mwen",
        "Ou Pa Ka Intimide-m" : "Map Sevi Yon Gran Bonyde",
        "Kisa Kris Renmen-m" : "Mouin Pa Konnin Pou", 
        "Yon Lot Nivo" : "Mwen Bezwen W Nan",
        "Mwen Pa Esclave Peche Anko" : "No longer Slaves" ,
        "Gen Bel Limye" : "Wi gen Lyme" ,
        "Lamou San Fen" : "Konbyen Mwen Dwe",
        "Mwen Chante" : "Se Pou Sa Ke",
        "Sou boua kalve" : "Tout Gras Bondye Se Pou Granmesi" ,
        "Yon Wa Damou" : "Beje Mwen Se",
        "Kot Jezi Te Pran-m" : "Sim Pam Ta Loue",
        "Tou Pre Kè Ou" : "Sere’m Pi Pre Ou",
        "Tout Ange Dwe Fas Ate" : "Onore Puisans Non Jezi",
        "Syel La Desan" : "Ala Yon Meveye Meveye Jou",
    }


]